// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX3KGM_fkb3zNmKBXRIwmkS6bs-lVqyg8',
    appId: '1:231349974349:web:3a46ba1f4524b154b8f304',
    messagingSenderId: '231349974349',
    projectId: 'campus-erp-jgu',
    authDomain: 'campus-erp-jgu.firebaseapp.com',
    storageBucket: 'campus-erp-jgu.firebasestorage.app',
    measurementId: 'G-GNN31DY1WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8z9f_Udb9e3vvW-0UgWwMsRuUAnCdYXk',
    appId: '1:231349974349:android:37598a8d2d5c2b90b8f304',
    messagingSenderId: '231349974349',
    projectId: 'campus-erp-jgu',
    storageBucket: 'campus-erp-jgu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwcU-JXnYMQZ8oVaWQEFIQ1p2enq_DtEE',
    appId: '1:231349974349:ios:8d85de4e83f80945b8f304',
    messagingSenderId: '231349974349',
    projectId: 'campus-erp-jgu',
    storageBucket: 'campus-erp-jgu.firebasestorage.app',
    iosClientId: '231349974349-3u7r7ikh6mu6j3ojt6urh9uokamdnaqt.apps.googleusercontent.com',
    iosBundleId: 'com.example.collegeErp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwcU-JXnYMQZ8oVaWQEFIQ1p2enq_DtEE',
    appId: '1:231349974349:ios:8d85de4e83f80945b8f304',
    messagingSenderId: '231349974349',
    projectId: 'campus-erp-jgu',
    storageBucket: 'campus-erp-jgu.firebasestorage.app',
    iosClientId: '231349974349-3u7r7ikh6mu6j3ojt6urh9uokamdnaqt.apps.googleusercontent.com',
    iosBundleId: 'com.example.collegeErp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX3KGM_fkb3zNmKBXRIwmkS6bs-lVqyg8',
    appId: '1:231349974349:web:ba82f7f5a0224258b8f304',
    messagingSenderId: '231349974349',
    projectId: 'campus-erp-jgu',
    authDomain: 'campus-erp-jgu.firebaseapp.com',
    storageBucket: 'campus-erp-jgu.firebasestorage.app',
    measurementId: 'G-MKY0JJ6RSH',
  );

}